name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/enriquecarvalho/amain-frontend:latest

    - name: Log in to GH Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the Docker images
      run: docker push ghcr.io/enriquecarvalho/amain-frontend:latest

    - name: Trigger update
      run: |
        curl -v -H "Authorization: Bearer '8&^TUs0E8^%7#%m^2%p9'" 168.75.103.41:9090/v1/update
